name : Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ make

      - name: Test 1 - Instantiation, Operations, Determinant
        run: |
              make file_name=test_1
              echo "Test case 1: passed"

      - name: Test 2 - Print, apply from utils.h, all possible multiplications
        run: |
              make file_name=test_2
              echo "Test case 2: passed"
      - name: Test 3 - Transpose
        run: |
              make file_name=test_3
              echo "Test case 3: passed"
      - name: Test 4 - LU Decomposition
        run: |
              make file_name=test_5
              echo "Test case 3: passed"              
              
      - name: Clean Files
        run: make clean